import { kv } from '@vercel/kv';

export const config = {
    runtime: 'edge',
};

interface TrendItem {
    topic: string;
    summary: string;
    articleCount: number;
}

interface CachedTrends {
    trends: TrendItem[];
    updatedAt: string;
}

interface TrendsResponse {
    daily: TrendItem[];
    weekly: TrendItem[];
    dailyUpdatedAt: string;
    weeklyUpdatedAt: string;
}

// This endpoint reads pre-computed trends from KV cache.
// Trends are generated by the fetch-feeds.js script running in GitHub Actions.
// This makes the API extremely fast - just a KV read, no computation.

export default async function handler(req: Request) {
    try {
        // Read both daily and weekly trends from KV
        const [dailyData, weeklyData] = await Promise.all([
            kv.get<CachedTrends>('daily_trends'),
            kv.get<CachedTrends>('weekly_trends'),
        ]);

        const response: TrendsResponse = {
            daily: dailyData?.trends || [],
            weekly: weeklyData?.trends || [],
            dailyUpdatedAt: dailyData?.updatedAt || '',
            weeklyUpdatedAt: weeklyData?.updatedAt || '',
        };

        // If no trends exist at all, return a helpful message
        if (response.daily.length === 0 && response.weekly.length === 0) {
            return new Response(
                JSON.stringify({
                    ...response,
                    message: 'Trends werden gerade generiert. Bitte versuche es in wenigen Minuten erneut.'
                }),
                {
                    status: 200,
                    headers: {
                        'Content-Type': 'application/json',
                        'Cache-Control': 's-maxage=60, stale-while-revalidate=120',
                    },
                }
            );
        }

        return new Response(JSON.stringify(response), {
            status: 200,
            headers: {
                'Content-Type': 'application/json',
                // Cache for 30 minutes on edge, allow stale for 1 hour
                'Cache-Control': 's-maxage=1800, stale-while-revalidate=3600',
            },
        });

    } catch (error) {
        console.error("API Error in /api/get-trends:", error);
        const message = error instanceof Error ? error.message : "An unknown error occurred.";
        return new Response(JSON.stringify({ error: message }), {
            status: 500,
            headers: { 'Content-Type': 'application/json' },
        });
    }
}